// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package enum

import (
	"go/ast"
	"go/token"
	"regexp"
	"strconv"

	"golang.org/x/tools/go/ast/astutil"
)

// Index describes enum lowering artifacts generated by FixSrc.
//
// It is built from parsed AST (after FixSrc ran), and used to rewrite enum
// constructor/pattern syntax into standard Go AST.
type Index struct {
	ctors    map[string]map[string]bool // typeName -> variant -> true (Type__Variant exists)
	payloads map[string]map[string]int  // typeName -> variant -> arity (payload struct exists)
	variants map[string]map[string]bool // typeName -> variant -> true (Type__Tag_Variant exists)
}

func BuildIndex(files []*ast.File) Index {
	idx := Index{
		ctors:    make(map[string]map[string]bool),
		payloads: make(map[string]map[string]int),
		variants: make(map[string]map[string]bool),
	}
	for _, f := range files {
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.FuncDecl:
				if d.Name == nil {
					continue
				}
				tn, vn, ok := splitEnumName(d.Name.Name)
				if !ok {
					continue
				}
				m := idx.ctors[tn]
				if m == nil {
					m = make(map[string]bool)
					idx.ctors[tn] = m
				}
				m[vn] = true

			case *ast.GenDecl:
				switch d.Tok {
				case token.TYPE:
					for _, s := range d.Specs {
						ts, _ := s.(*ast.TypeSpec)
						if ts == nil || ts.Name == nil {
							continue
						}
						tn, vn, ok := splitPayloadName(ts.Name.Name)
						if !ok {
							continue
						}
						st, _ := ts.Type.(*ast.StructType)
						if st == nil {
							continue
						}
						arity := 0
						for _, fld := range st.Fields.List {
							// Count only F0/F1/... fields.
							for _, n := range fld.Names {
								if n != nil && payloadFieldRx.MatchString(n.Name) {
									arity++
								}
							}
						}
						m := idx.payloads[tn]
						if m == nil {
							m = make(map[string]int)
							idx.payloads[tn] = m
						}
						m[vn] = arity
					}
				case token.CONST:
					// Record declared variants from tag const names.
					for _, s := range d.Specs {
						vs, _ := s.(*ast.ValueSpec)
						if vs == nil {
							continue
						}
						for _, n := range vs.Names {
							if n == nil {
								continue
							}
							tn, vn, ok := splitTagName(n.Name)
							if !ok {
								continue
							}
							m := idx.variants[tn]
							if m == nil {
								m = make(map[string]bool)
								idx.variants[tn] = m
							}
							m[vn] = true
						}
					}
				}
			}
		}
	}
	return idx
}

func (idx Index) HasAny() bool {
	return len(idx.ctors) > 0
}

func (idx Index) Variants(typeName string) map[string]bool {
	return idx.variants[typeName]
}

// RewriteFiles rewrites enum constructor + switch/case patterns in-place.
//
// It is intentionally conservative: if we can't confidently rewrite a construct,
// we leave it alone.
func RewriteFiles(files []*ast.File, idx Index) {
	r := &rewriter{idx: idx}
	for _, f := range files {
		r.rewriteFile(f)
	}
}

type rewriter struct {
	idx    Index
	tmpSwN int
}

func (r *rewriter) rewriteFile(f *ast.File) {
	astutil.Apply(f, func(c *astutil.Cursor) bool {
		switch n := c.Node().(type) {
		case *ast.CallExpr:
			// Rewrite constructor calls: T.Variant(args...) -> T__Variant(args...)
			if sel, ok := n.Fun.(*ast.SelectorExpr); ok {
				if newFun, ok := r.rewriteCtorSel(sel, true); ok {
					n.Fun = newFun
					return true
				}
			}
		case *ast.SelectorExpr:
			// Rewrite unit variant value: T.Variant -> T__Variant()
			// But skip if this selector is the callee of a call (handled above).
			if parent := c.Parent(); parent != nil {
				if _, ok := parent.(*ast.CallExpr); ok && c.Name() == "Fun" {
					return true
				}
			}
			if newExpr, ok := r.rewriteCtorSel(n, false); ok {
				c.Replace(newExpr)
				return false
			}
		case *ast.SwitchStmt:
			if newStmt, ok := r.rewriteEnumSwitch(n); ok {
				c.Replace(newStmt)
				return false
			}
		}
		return true
	}, nil)
}

type pattern struct {
	typeName string
	typeArgs ast.Expr // may be nil
	variant  string
	call     *ast.CallExpr     // non-nil for payload patterns
	sel      *ast.SelectorExpr // non-nil for unit patterns
}

func parsePatternExpr(e ast.Expr) (pattern, bool) {
	switch e := e.(type) {
	case *ast.CallExpr:
		sel, ok := e.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel == nil {
			return pattern{}, false
		}
		tn, targs, ok := baseTypeAndArgs(sel.X)
		if !ok {
			return pattern{}, false
		}
		return pattern{typeName: tn, typeArgs: targs, variant: sel.Sel.Name, call: e}, true
	case *ast.SelectorExpr:
		if e.Sel == nil {
			return pattern{}, false
		}
		tn, targs, ok := baseTypeAndArgs(e.X)
		if !ok {
			return pattern{}, false
		}
		return pattern{typeName: tn, typeArgs: targs, variant: e.Sel.Name, sel: e}, true
	default:
		return pattern{}, false
	}
}

func wildcardOnlyArgs(args []ast.Expr) bool {
	for _, a := range args {
		id, ok := a.(*ast.Ident)
		if !ok {
			return false
		}
		if id.Name != "_" {
			return false
		}
	}
	return true
}

// rewriteCtorSel rewrites selector expressions of the form:
// - T.Variant (unit) -> CallExpr{Fun: T__Variant, Args: nil}
// - T.Variant(args...) call -> just rewrite the callee expression
//
// Supports generic constructors:
// - T[int].Variant(...) -> T__Variant[int](...)
func (r *rewriter) rewriteCtorSel(sel *ast.SelectorExpr, inCall bool) (ast.Expr, bool) {
	if sel == nil || sel.Sel == nil {
		return nil, false
	}

	typeName, targs, ok := baseTypeAndArgs(sel.X)
	if !ok {
		return nil, false
	}
	variant := sel.Sel.Name
	if !r.isCtor(typeName, variant) {
		return nil, false
	}

	fnIdent := ast.NewIdent(typeName + "__" + variant)
	var fun ast.Expr = fnIdent
	if targs != nil {
		fun = &ast.IndexExpr{X: fnIdent, Index: targs}
	}
	if inCall {
		return fun, true
	}
	return &ast.CallExpr{Fun: fun, Lparen: sel.Sel.Pos(), Args: nil, Rparen: sel.Sel.End()}, true
}

func (r *rewriter) isCtor(typeName, variant string) bool {
	m := r.idx.ctors[typeName]
	return m != nil && m[variant]
}

func (r *rewriter) arity(typeName, variant string) (int, bool) {
	m := r.idx.payloads[typeName]
	if m == nil {
		return 0, false
	}
	n, ok := m[variant]
	return n, ok
}

func (r *rewriter) rewriteEnumSwitch(sw *ast.SwitchStmt) (ast.Stmt, bool) {
	if sw == nil || sw.Tag == nil || sw.Body == nil {
		return nil, false
	}

	// Find first pattern case to determine enum type + (optional) type args.
	var (
		patType string
		patTArg ast.Expr
	)
	for _, s := range sw.Body.List {
		cc, _ := s.(*ast.CaseClause)
		if cc == nil || len(cc.List) == 0 {
			continue
		}
		for _, e := range cc.List {
			p, ok := parsePatternExpr(e)
			if !ok {
				continue
			}
			if !r.isCtor(p.typeName, p.variant) {
				continue
			}
			patType, patTArg = p.typeName, p.typeArgs
			break
		}
		if patType != "" {
			break
		}
	}
	if patType == "" {
		return nil, false
	}

	// Create: _mygo_swN := <tag>; switch _mygo_swN._tag { ... }
	tmpName := "_mygo_sw" + strconv.Itoa(r.tmpSwN)
	r.tmpSwN++
	tmpIdent := ast.NewIdent(tmpName)
	tmpRef1 := ast.NewIdent(tmpName)
	tmpRef2 := ast.NewIdent(tmpName)

	assign := &ast.AssignStmt{
		Lhs:    []ast.Expr{tmpIdent},
		TokPos: sw.Switch,
		Tok:    token.DEFINE,
		Rhs:    []ast.Expr{sw.Tag},
	}

	newSwitch := *sw
	newSwitch.Tag = &ast.SelectorExpr{X: tmpRef1, Sel: ast.NewIdent("_tag")}

	// Rewrite case clauses.
	newBody := &ast.BlockStmt{Lbrace: sw.Body.Lbrace, Rbrace: sw.Body.Rbrace}
	for _, s := range sw.Body.List {
		cc, _ := s.(*ast.CaseClause)
		if cc == nil {
			newBody.List = append(newBody.List, s)
			continue
		}
		// default:
		if len(cc.List) == 0 {
			newBody.List = append(newBody.List, s)
			continue
		}

		// Multi-pattern support (no bindings):
		// - unit variants: case T.Point, T.Nil:
		// - wildcard-only payload: case T.Rect(_, _), T.Circle(_):
		//
		// If any pattern binds variables (non-underscore idents), we only support
		// singleton pattern cases (existing behavior).
		var (
			tagList        []ast.Expr
			singleBindPat  *pattern
			singleBindTArg ast.Expr
			singleBindSel  *ast.SelectorExpr
		)
		okAll := true
		for _, e := range cc.List {
			p, ok := parsePatternExpr(e)
			if !ok || p.typeName != patType || p.variant == "" || !r.isCtor(patType, p.variant) {
				okAll = false
				break
			}

			if p.call == nil {
				// unit variant
				tagList = append(tagList, ast.NewIdent(patType+"__Tag_"+p.variant))
				continue
			}

			arity, hasPayload := r.arity(patType, p.variant)
			if hasPayload && arity != len(p.call.Args) {
				okAll = false
				break
			}
			if hasPayload && arity > 0 && !wildcardOnlyArgs(p.call.Args) {
				// binding case; only allow singleton
				if len(cc.List) != 1 {
					okAll = false
					break
				}
				singleBindPat = &p
				singleBindTArg = p.typeArgs
				sel, _ := p.call.Fun.(*ast.SelectorExpr)
				singleBindSel = sel
				continue
			}
			// payload but wildcard-only: no bindings, safe to add to tag list
			tagList = append(tagList, ast.NewIdent(patType+"__Tag_"+p.variant))
		}
		if !okAll {
			newBody.List = append(newBody.List, s)
			continue
		}

		// Single binding pattern (existing behavior), but allow through our new parser.
		if singleBindPat != nil && singleBindSel != nil && singleBindPat.call != nil {
			vname := singleBindPat.variant
			tagConst := ast.NewIdent(patType + "__Tag_" + vname)

			arity, hasPayload := r.arity(patType, vname)
			_ = arity

			// Build bindings.
			var prefix []ast.Stmt
			if hasPayload && len(singleBindPat.call.Args) > 0 {
				// p := _mygo_swN._payload.(T__payload_Variant[targs])
				pName := ast.NewIdent("_mygo_p")
				pRef := ast.NewIdent("_mygo_p")

				payloadIdent := ast.NewIdent(patType + "__payload_" + vname)
				var payloadType ast.Expr = payloadIdent
				if singleBindPat.typeArgs != nil {
					payloadType = &ast.IndexExpr{X: payloadIdent, Index: singleBindPat.typeArgs}
				} else if singleBindTArg != nil {
					payloadType = &ast.IndexExpr{X: payloadIdent, Index: singleBindTArg}
				} else if patTArg != nil {
					payloadType = &ast.IndexExpr{X: payloadIdent, Index: patTArg}
				}

				typeAssert := &ast.TypeAssertExpr{
					X:      &ast.SelectorExpr{X: tmpRef2, Sel: ast.NewIdent("_payload")},
					Lparen: singleBindPat.call.Lparen,
					Type:   payloadType,
					Rparen: singleBindPat.call.Rparen,
				}
				prefix = append(prefix, &ast.AssignStmt{
					Lhs:    []ast.Expr{pName},
					TokPos: cc.Case,
					Tok:    token.DEFINE,
					Rhs:    []ast.Expr{typeAssert},
				})

				for i, a := range singleBindPat.call.Args {
					id, ok := a.(*ast.Ident)
					if !ok {
						continue
					}
					if id.Name == "_" {
						continue
					}
					prefix = append(prefix, &ast.AssignStmt{
						Lhs:    []ast.Expr{ast.NewIdent(id.Name)},
						TokPos: id.Pos(),
						Tok:    token.DEFINE,
						Rhs: []ast.Expr{
							&ast.SelectorExpr{X: pRef, Sel: ast.NewIdent("F" + strconv.Itoa(i))},
						},
					})
				}
			}

			newCC := *cc
			newCC.List = []ast.Expr{tagConst}
			newCC.Body = append(prefix, cc.Body...)
			newBody.List = append(newBody.List, &newCC)
			continue
		}

		// No-binding patterns (possibly multiple): just rewrite the case list.
		newCC := *cc
		newCC.List = tagList
		newBody.List = append(newBody.List, &newCC)
		continue

	}
	newSwitch.Body = newBody

	blk := &ast.BlockStmt{
		Lbrace: sw.Switch,
		List:   []ast.Stmt{assign, &newSwitch},
		Rbrace: sw.End(),
	}
	return blk, true
}

// baseTypeAndArgs extracts type name and optional type argument expression from:
// - Ident("T")                    => ("T", nil, true)
// - IndexExpr{X: Ident("T"), ...} => ("T", IndexExpr.Index, true)
func baseTypeAndArgs(x ast.Expr) (string, ast.Expr, bool) {
	switch x := x.(type) {
	case *ast.Ident:
		return x.Name, nil, true
	case *ast.IndexExpr:
		if id, ok := x.X.(*ast.Ident); ok {
			return id.Name, x.Index, true
		}
	}
	return "", nil, false
}

var enumNameRx = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*)__([A-Za-z_][A-Za-z0-9_]*)$`)
var payloadNameRx = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*)__payload_([A-Za-z_][A-Za-z0-9_]*)$`)
var tagNameRx = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*)__Tag_([A-Za-z_][A-Za-z0-9_]*)$`)
var payloadFieldRx = regexp.MustCompile(`^F[0-9]+$`)

func splitEnumName(fn string) (typeName, variant string, ok bool) {
	m := enumNameRx.FindStringSubmatch(fn)
	if len(m) != 3 {
		return "", "", false
	}
	return m[1], m[2], true
}

func splitPayloadName(tn string) (typeName, variant string, ok bool) {
	m := payloadNameRx.FindStringSubmatch(tn)
	if len(m) != 3 {
		return "", "", false
	}
	return m[1], m[2], true
}

func splitTagName(nm string) (typeName, variant string, ok bool) {
	m := tagNameRx.FindStringSubmatch(nm)
	if len(m) != 3 {
		return "", "", false
	}
	return m[1], m[2], true
}
